# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OperaçãoRicardoFranco
                                 A QGIS plugin
 Identificador de Crimes Transfronteiriços utilizando Inteligência Artificial
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-21
        copyright            : (C) 2024 by Matheus Alves Silva, Reginaldo Pereira da Silva Filho
        email                : reginaldo.silva@ime.eb.br
                               matheus.silva@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Matheus Alves Silva, Reginaldo Pereira da Silva Filho'
__date__ = '2024-11-21'
__copyright__ = '(C) 2024 by Matheus Alves Silva, Reginaldo Pereira da Silva Filho'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import processing

from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .operacao_ricardo_franco_provider import IdentificadorCrimesFronteirasProvider

class IdentificadorIlicitosIA(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = IdentificadorCrimesFronteirasProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        
        icon_path = os.path.join(os.path.dirname(__file__), "icon-orf-resized.png")
        self.action = QAction(
              QIcon(icon_path),
              u"Identificador de Garimpo Ilegal na Amazônia", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToRasterMenu(u"&Projeto SIMGEO 2025", self.action)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        self.iface.removePluginRasterMenu(u"&Projeto SIMGEO 2025", self.action)
        self.iface.removeToolBarIcon(self.action)

    def run(self):        
        processing.execAlgorithmDialog("ProjetoSIMGEO2025:Identificador de Garimpo Ilegal na Amazônia")
